# Generated by Django 4.2.2 on 2023-10-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serNombre', models.CharField(db_comment='Nombre del tratamiento', max_length=60, unique=True)),
                ('serTipo', models.CharField(db_comment='Tipo de tratamiento, si es cirugia, revision', max_length=40)),
                ('serFoto', models.ImageField(blank=True, db_comment='Foto del Servicio', null=True, upload_to='fotos/')),
                ('serDirigido', models.CharField(choices=[('Animales Domesticos', 'Animales Domesticos'), ('Animales De Granja', 'Animales De Granja')], db_comment='A que tipo de animales va dirigido el animal', max_length=30, null=True)),
                ('serPrecio', models.IntegerField(db_comment='Precio del Tratamiento')),
                ('serEstado', models.CharField(choices=[('Disponible', 'Disponible'), ('NoDisponible', 'NoDisponible')], default='Disponible', max_length=13, null=True)),
                ('serDescripcion', models.TextField(db_comment='Descripcion Del servicio')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
            ],
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='traEmpleado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fechaHoraCreacion',
            new_name='fechaHoraCreacio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='ciTratamiento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='peCodigoComprobante',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='peDetPedido',
        ),
        migrations.AddField(
            model_name='cita',
            name='ciFecha',
            field=models.DateField(db_comment='Fecha de la cita', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='ciHora',
            field=models.TimeField(db_comment='Hora de la cita', null=True),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='conFecha',
            field=models.DateField(db_comment='Fecha en la que registro el mensaje', null=True),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='conHora',
            field=models.TimeField(db_comment='Hora en la que registro el mensjae', null=True),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='conResponder',
            field=models.TextField(db_comment='Respuesta por parte del administrador', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='detDescuentoPorcentaje',
            field=models.IntegerField(db_comment='Descuento Porcentaje', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='detDescuentoPrecio',
            field=models.IntegerField(db_comment='Precio Del Descuento', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='detPedido',
            field=models.ForeignKey(db_comment='Detalle envio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appVeterinaria.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='detPrecioVendidoProducto',
            field=models.IntegerField(db_comment='Precio Por el que se vendio el producto', null=True),
        ),
        migrations.AddField(
            model_name='detellaenvio',
            name='detDepartamento',
            field=models.CharField(db_comment='Departamento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detellaenvio',
            name='detDireccion',
            field=models.CharField(db_comment='Direccion', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detellaenvio',
            name='detMunicipio',
            field=models.CharField(db_comment='Municipio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='emUsuario',
            field=models.CharField(choices=[('Creado', 'Creado'), ('SinCrear', 'SinCrear')], default='SinCrear', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peCodigoPedido',
            field=models.IntegerField(db_comment='Codigo del comprobante', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peDescuento',
            field=models.IntegerField(db_comment='DescuentoTotal', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peFecha',
            field=models.DateField(db_comment='Fecha pedido', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peHora',
            field=models.TimeField(db_comment='Hora pedido', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proDescuento',
            field=models.IntegerField(db_comment='Porcentaje del descuento, del 1 a 100', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido')], db_comment='Estado del usuario', default='Activo', max_length=11),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='detPrecio',
            field=models.IntegerField(db_comment='Precio por cada producto con descuento'),
        ),
        migrations.AlterField(
            model_name='detellaenvio',
            name='detDescripcion',
            field=models.TextField(db_comment='Descripcion de la direccion', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detellaenvio',
            name='detNombreDestinatario',
            field=models.CharField(db_comment='Nombre de aquien se envia', max_length=60),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='masFoto',
            field=models.ImageField(blank=True, db_comment='Foto de la mascota', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='peEstado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Solicitado', 'Solicitado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Pago Cargado', 'Pago Cargado')], db_comment='estado del pedido', max_length=14),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='peFormaPago',
            field=models.CharField(db_comment='Forma de pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proFotoComprobante',
            field=models.ImageField(blank=True, db_comment='Foto del comprobante', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proEstado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('Vencido', 'Vencido'), ('Eliminado', 'Eliminado'), ('Promocion', 'Promocion')], db_comment='Estado del produco', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFoto',
            field=models.ImageField(blank=True, db_comment='Foto del Usuario', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTelefono',
            field=models.IntegerField(db_comment='Telefono del usuario'),
        ),
        migrations.DeleteModel(
            name='FormaDePago',
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
        migrations.AddField(
            model_name='servicio',
            name='serEmpleado',
            field=models.ForeignKey(db_comment='El empleado que atiende este servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appVeterinaria.empleado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='ciServicio',
            field=models.ForeignKey(db_comment='Servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appVeterinaria.servicio'),
        ),
    ]
