# Generated by Django 4.2.2 on 2023-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCodigo',
            field=models.IntegerField(db_comment='Codigo Recuperacion', null=True),
        ),
    ]
