# Generated by Django 4.2.2 on 2023-06-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_user_usercodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCodigo',
            field=models.IntegerField(db_comment='Codigo Recuperacion', null=True, unique=True),
        ),
    ]
