# Generated by Django 4.2.2 on 2023-08-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='peFormaPago',
            field=models.CharField(db_comment='Forma de pago', max_length=20),
        ),
        migrations.DeleteModel(
            name='FormaDePago',
        ),
    ]
