# Generated by Django 4.2.2 on 2023-08-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_servicio_alter_cita_citratamiento_delete_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='ciTratamiento',
        ),
        migrations.AddField(
            model_name='cita',
            name='ciFecha',
            field=models.DateTimeField(db_comment='Fecha de la cita', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='ciHora',
            field=models.TimeField(db_comment='Hora de la cita', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='ciServicio',
            field=models.ForeignKey(db_comment='Servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appVeterinaria.servicio'),
        ),
    ]
