# Generated by Django 4.2.2 on 2023-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_servicio_remove_tratamiento_traempleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userTelefono',
            field=models.BigIntegerField(db_comment='Telefono del usuario', null=True),
        ),
    ]
