# Generated by Django 4.2.2 on 2023-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0003_alter_user_usercodigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conNombre', models.CharField(db_comment=' Nombre De La Persona Que Se Va Contactar', max_length=50)),
                ('conEmail', models.CharField(db_comment='Direccion del correo electronico', max_length=30, unique=True)),
                ('conNumeroTe', models.IntegerField(db_comment='Telefono del usuario Que Se Contacta', null=True)),
                ('conMensaje', models.CharField(db_comment='Mensaje Que El Usuario enviar para contartacnos', max_length=150, null=True)),
            ],
        ),
    ]
