# Generated by Django 4.2.2 on 2023-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0003_alter_user_usertelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='conNumeroTe',
            field=models.BigIntegerField(db_comment='Telefono del usuario Que Se Contacta', null=True),
        ),
        migrations.AlterField(
            model_name='detellaenvio',
            name='detTelefonoDestinatario',
            field=models.BigIntegerField(db_comment='Telefono del quien recibe'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emTelefono',
            field=models.BigIntegerField(db_comment='Numero telefonico del empleado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proTelefono',
            field=models.BigIntegerField(db_comment='Telefono de la empresa'),
        ),
    ]
