# Generated by Django 4.2.2 on 2023-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0003_alter_pedido_peformapago_delete_formadepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='peEstado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Solicitado', 'Solicitado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Pago Exitoso', 'Pago Exitoso')], db_comment='estado del pedido', max_length=14),
        ),
    ]
