# Generated by Django 4.2.2 on 2023-10-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0004_alter_contactanos_connumerote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proCantidad',
            field=models.BigIntegerField(db_comment='Cantidad_Disponible', default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proCantidadVendida',
            field=models.BigIntegerField(db_comment='Cantidad_Disponible', default=0, null=True),
        ),
    ]
