# Generated by Django 4.2.2 on 2023-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0004_contactanos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='emCorreo',
            field=models.CharField(db_comment='Direccion del correo electronico', max_length=48, unique=True),
        ),
    ]
