# Generated by Django 4.2.2 on 2023-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0005_alter_pedido_peestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proFotoComprobante',
            field=models.ImageField(blank=True, db_comment='Foto del comprobante', null=True, upload_to='fotos/'),
        ),
    ]
