# Generated by Django 4.2.2 on 2023-06-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0005_alter_empleado_emcorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='traEmpleado',
            field=models.ForeignKey(db_comment='El empleado que atiende este servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='appVeterinaria.empleado'),
        ),
    ]
