# Generated by Django 4.2.2 on 2023-10-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0005_producto_procantidad_producto_procantidadvendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proDescuento',
            field=models.IntegerField(db_comment='Porcentaje del descuento, del 1 a 100', default=0, null=True),
        ),
    ]
