# Generated by Django 4.2.2 on 2023-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0005_alter_servicio_serempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='ciFecha',
            field=models.DateField(db_comment='Fecha de la cita', null=True),
        ),
    ]
