# Generated by Django 4.2.2 on 2023-08-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0006_alter_pedido_profotocomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='peFecha',
            field=models.DateField(db_comment='Fecha pedido', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peHora',
            field=models.TimeField(db_comment='Hora pedido', null=True),
        ),
    ]
