# Generated by Django 4.2.2 on 2023-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0007_pedido_pefecha_pedido_pehora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='masFoto',
            field=models.ImageField(blank=True, db_comment='Foto de la mascota', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFoto',
            field=models.ImageField(blank=True, db_comment='Foto del Usuario', null=True, upload_to='fotos/'),
        ),
    ]
