# Generated by Django 4.2.2 on 2023-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0008_alter_mascota_masfoto_alter_user_userfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido')], db_comment='Estado del usuario', default='Activo', max_length=11),
        ),
    ]
